@local = http://localhost:5000

###

POST {{local}}/register
Content-Type: application/json

{
    "name":"yoram",
    "email": "lord@email.com",
    "password": "Aa1234567"
}

###
GET {{local}}/api/profile
Content-Type: application/json

{
    
}